import Alert from './Alert';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

// Original branch
// "https://www.figma.com/design/OYkYP4pC9jwS7j2qafwmiv/?node-id=56%3A4727"
figma.connect(
  Alert,
  'https://www.figma.com/design/OYkYP4pC9jwS7j2qafwmiv/branch/EY3W2duP5LJfOrHYdEU0ps/Design-System-Library?m=auto&node-id=56-4727&t=NzUAuvg76hM0oNJF-1',
  {
    props: {
      // No matching props could be found for these Figma properties:
      heading: figma.string('Alert Title'),
      children: figma.string('Alert body text'),
      heading: figma.boolean('Has title'),
      // "hasBodyText": figma.boolean('Has body text'),
      // "hasButton2": figma.boolean('Has Button 2'),
      // "hasButton1": figma.boolean('Has Button 1'),
      // "hasLinkLine": figma.boolean('Has Link line'),
      // "hasList": figma.boolean('Has list'),
      // Remap --
      hideIcon: figma.boolean('Has icon'),
      variation: figma.enum('Alert Type', {
        Info: 'informational',
        Success: 'success',
        Warning: 'warning',
        Error: 'error',
      }),
      weight: figma.boolean('Lightweight'),
    },
    example: (props) => <Alert {...props} />,
  }
);
