import themeColors from './core-theme'

export const components = {
  // alert
  'alert__background-color': themeColors['primary-alt-lightest'],
  'alert__background-color--error': themeColors['error-lightest'],
  'alert__background-color--lightweight': themeColors['white'],
  'alert__background-color--success': themeColors['success-lightest'],
  'alert__background-color--warn': themeColors['warn-lightest'],
  'alert__bar-width': spacer[1],
  'alert__border-left-color': themeColors['primary-alt'],
  'alert__border-color--error': themeColors.error,
  'alert__border-color--success': themeColors.success,
  'alert__border-color--warn': themeColors.warn,
  'alert__font-color': themeColors['base'],
  'alert__icon-size': spacer[5],
  alert__padding: spacer[2],
  'alert-link__font-color': themeColors['primary-darker'],
  'alert-link__font-color--hover': themeColors['primary-darkest'],
  'alert-link__font-color--focus': themeColors['primary-darkest'],
  'alert-link__font-color--active': themeColors['primary-darkest'],
  // autocomplete
  'autocomplete-list__background-color': themeColors.white,
  'autocomplete-list__border-color': themeColors['gray-lighter'],
  'autocomplete-list-item__font-color': themeColors.primary,
  'autocomplete-list-item__background-color--active': themeColors['primary-alt-darkest'],
  'autocomplete-list-item__font-color--active': themeColors.white,
  'autocomplete-list-item-message__font-color': themeColors.muted,
  // badge
  'badge__background-color': themeColors.gray,
  'badge__font-color': themeColors.white,
  'badge__background-color--alert': themeColors.error,
  'badge__background-color--info': themeColors.primary,
  'badge__background-color--success': themeColors.success,
  'badge__background-color--warn': themeColors.warn,
  'badge__font-color--warn': themeColors.base,
  'badge__border-radius': radius.pill,
  // button
  'button__border-radius': radius.default,
  'button__border-width': '1px',
  'button__background-color': themeColors.white,
  'button__background-color--active': themeColors.white,
  'button__background-color--disabled': themeColors.white,
  'button__background-color--hover': themeColors['primary-darker'],
  'button__border-color': themeColors.primary,
  'button__border-color--active': themeColors['primary-darkest'],
  'button__border-color--disabled': themeColors['gray-lighter'],
  'button__border-color--hover': themeColors['primary-darker'],
  button__color: themeColors.primary,
  'button__color--active': themeColors['primary-darkest'],
  'button__color--disabled': themeColors['gray-lighter'],
  'button__color--hover': themeColors['primary-darker'],
  // button - inverse
  'button-inverse__background-color': themeColors['background-inverse'],
  'button-inverse__background-color--disabled': themeColors['background-inverse'],
  'button-inverse__background-color--focus': themeColors['background-inverse'],
  'button-inverse__border-color': themeColors['border-inverse'],
  'button-inverse__border-color--active': hexOpacity(themeColors['border-inverse'], 60),
  'button-inverse__border-color--disabled': themeColors['gray-lighter'],
  'button-inverse__border-color--hover': hexOpacity(themeColors['base-inverse'], 80),
  'button-inverse__color': themeColors['base-inverse'],
  'button-inverse__color--active': hexOpacity(themeColors['base-inverse'], 60),
  'button-inverse__color--disabled': themeColors['gray-lighter'],
  'button-inverse__color--hover': hexOpacity(themeColors['base-inverse'], 80),
  // button - transparent
  'button-transparent__color--active': themeColors['primary-darkest'],
  'button-transparent__background-color--disabled': themeColors['gray-lighter'],
  'button-transparend__color--disabled': themeColors['gray-dark'],
  // button - inverse transparent
  'button-inverse-transparent__background-color': themeColors['gray-lighter'],
  'button-inverse-transparent__color': themeColors['gray-dark'],
  // button - primary & status buttons
  'button-primary__background-color': themeColors.primary,
  'button-primary__background-color--hover': themeColors['primary-darker'],
  'button-primary__background-color--active': themeColors['primary-darkest'],
  // choice + choicelist
  'choice__background-color': themeColors.background,
  'choice__background-color--checked': themeColors.primary,
  'choice__background-color--disabled': themeColors['gray-lighter'],
  'choice__background-color--inverse': themeColors.transparent,
  'choice__background-color--disabled--inverse': hexOpacity(themeColors['muted-inverse'], 15),
  'choice__border-color': themeColors.base,
  'choice__border-color--checked': themeColors.primary,
  'choice__border-color--disabled': themeColors['gray-light'],
  'choice__border-color--error': themeColors.error,
  'choice__border-color--inverse': themeColors.white,
  'choice__border-color--left': themeColors.primary,
  'choice__border-color--focus': themeColors['primary-darker'],
  'choice__border-color--disabled--inverse': themeColors['gray-light'],
  'choice__border-radius': '0px',
  'choice__border-width': '2px',
  'choice__color--unchecked': themeColors.white,
  'choice__color--disabled': themeColors.muted,
  choice__size: spacer[4],
  'choice__size--small': '20px',
  'choice__size-radio': '22px',
  'choice__size-radio--small': '12px',
  'choice-label__color--disabled': themeColors.muted,
  'choice-label__color--disabled--inverse': themeColors['muted-inverse'],
  // dialog
  'dialog__background-color': themeColors.white,
  dialog__padding: spacer[4],
  'dialog-overlay__background-color': themeColors['background-dialog-mask'],
  // drawer
  'drawer__animation-timing': animation['speed-2'],
  'drawer__background-color': themeColors.background,
  'drawer__border-color': themeColors.border,
  'drawer-close__color': themeColors.black,
  'drawer-header__background-color': themeColors['gray-lightest'],
  'drawer-footer__background-color': themeColors['primary-alt-lightest'],
  'drawer-toggle__background-color--hover': themeColors['primary-alt'],
  'drawer-toggle__color--hover': themeColors.white,
  'drawer-toggle__background-color--hover--inverse': themeColors.white,
  'drawer-toggle__color--hover--inverse': themeColors['gray-darker'],
  // dropdown
  'dropdown__background-color': themeColors.white,
  'dropdown__icon-size': '10px',
  // filter chip
  'filter-chip__border-radius': radius.pill,
  'filter-chip__background-color': themeColors['primary-alt-lightest'],
  'filter-chip__border-color': themeColors.primary,
  'filter-chip__color': themeColors.base,
  'filter-chip__background-color--active': themeColors.primary,
  'filter-chip__border-color--active': themeColors.primary,
  'filter-chip__color--active': themeColors.white,
  'filter-chip-icon__color': themeColors.base,
  'filter-chip-icon__color-active': themeColors.white,
  // forms
  'form-label__color--inverse': themeColors['base-inverse'],
  'form__max-width': '460px',
  'form__max-width--small': '6em',
  'form__max-width--medium': '12em',
  'form-hint__color': themeColors.muted,
  'form-hint__color--inverse': themeColors['muted-inverse'],
  'form-error__color': themeColors.error,
  'form-error__color--inverse': themeColors['error-light'],
  // link
  link__color: themeColors.primary,
  'link__color--visited': themeColors.visited,
  'link__color--hover': themeColors['primary-darker'],
  'link__color--active': themeColors['primary-darkest'],
  'link-inverse__color': themeColors['base-inverse'],
  'link-inverse__color--visited': themeColors['muted-inverse'],
  'link-inverse__color--hover': themeColors['muted-inverse'],
  'link-inverse__color--active': themeColors['muted-inverse'],
  'link__text-decoration--thickness': '1px',
  'link__text-decoration--thickness--hover': '1px',
  'link__text-decoration--offset': 'auto',
  // pagination
  'pagination-link__color': themeColors.primary,
  'pagination-link__color--hover': themeColors['primary-darker'],
  'pagination-link__color--active': themeColors['primary-darkest'],
  'pagination-link__color--focus': themeColors['primary-darker'],
  'pagination-link__color--disabled': themeColors['gray-lighter'],
  'pagination-current-page__color': themeColors.base,
  'pagination-overflow__color': themeColors.gray,
  'pagination-page-count__color': themeColors.gray,
  // review
  'review__border-color': themeColors['border'],
  // steplist
  steplist__color: themeColors.muted,
  'steplist__color--current': themeColors.primary,
  'steplist__background-color--current': themeColors.primary,
  'steplist-step__color': themeColors.muted,
  'steplist-step__border-color': themeColors.border,
  'steplist-step__border-color--default': themeColors.muted,
  'steplist-step__color--current': themeColors.white,
  'steplist-step__color--completed': themeColors.base,
  'steplist-step__background-color--completed': themeColors.base,
  // spinner
  'spinner__background-color': themeColors.background,
  spinner__color: themeColors.base,
  'spinner__background-color--inverse': themeColors['background-inverse'],
  'spinner__color--inverse': themeColors.white,
  // text input
  'text-input__line-height': 1.3,
  'text-input__background-color--disabled': themeColors['gray-lighter'],
  'text-input__border-width': '2px',
  'text-input__border-color': themeColors.base,
  'text-input__border-color--disabled': themeColors['gray-light'],
  'text-input__border-color--error': themeColors.error,
  'text-input__border-color--error--inverse': themeColors['error-light'],
  'text-input__border-color--inverse': themeColors.black,
  'text-input__border-color--success': themeColors['success-light'],
  'text-input__color': themeColors.base,
  'text-input__padding': spacer[1],
  'text-input__border-radius': radius.default,
  // vertical navigation
  'vertical-nav-item__background-color--hover': themeColors['gray-lightest'],
  'vertical-nav-item__color--hover': themeColors.primary,
  'vertical-nav-item__border-color': themeColors.gray,
  'vertical-nav-label__color': themeColors.base,
  'vertical-nav-label-icon__color': themeColors.base,
  'vertical-nav-label__border-color--current': themeColors.primary,
  'vertical-nav-label__color--current': themeColors.primary,
};

export default components;
