import Accordion from './Accordion';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Accordion,
  'https://www.figma.com/design/OYkYP4pC9jwS7j2qafwmiv/?node-id=22112%3A25734',
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "open": figma.boolean('Open')
    },
    example: (props) => <Accordion {...props} />,
  }
);
