import { FileDescriptor } from './types';
import { flatten } from './utility';
import { writeFile } from './file';

/**
 * Some sass variables are used in loops in sass. These variables cannot be mapped to css variables because sass will error.
 * This list should include the variable names to be ignored in the sass -> css variable -> value mappings
 *
 * Instead, these values will have a direct sass variable -> value definition
 */
const variableIgnoreList: string[] = [
  'font-sans',
  'font-seriff',
  'grid-columns',
  'media-width-xs',
  'media-width-sm',
  'media-width-md',
  'media-width-lg',
  'media-width-xl',
  'spacer-1',
  'spacer-2',
  'spacer-3',
  'spacer-4',
  'spacer-5',
  'spacer-6',
  'spacer-7',
  'spacer-none',
  'spacer-half',
];

/**
 * Formats an object containing key/value token pairs as a single string containing
 * the formatted values ready to be written to a SCSS file, including line breaks
 *
 * @param items - The object containing the key/value pairs
 * @param prefix - The prefix to be appended to each key on export
 * @param formatter - A function which takes a key, value and returns a formatted key, value string
 * @param separator - The separator between the prefix and key
 * @returns A string which contains all formatted key/value pairs
 */
const formatTokensAsCssVars = (
  items: Record<string, any>,
  prefix: string,
  formatter: (name: string, value: string) => string,
  separator: string
): string => {
  let SCSS = '';
  Object.entries(items).forEach(([name, value]) => {
    // global objects in themes are not prefixed by the token type
    name = prefix === 'global' ? name : `${prefix}${separator}${name}`;
    SCSS += formatter(name, value);
  });
  return SCSS;
};

/**
 * Writes a .scss file that maps a scss variable to a css variable
 *
 * @param filename - name of file to be created
 * @param file -  a single FileDescriptor item generated by getFileDescriptors
 * @param importedModule - module data
 * @param sep - separator string between prefix and key
 */
const writeMap = (filename: string, file: FileDescriptor, importedModule: any, sep: string) => {
  let tokenItems: Record<string, any>;
  let output = '';

  Object.entries(importedModule.default).forEach(([section]) => {
    tokenItems = flatten(importedModule.default[section]);
    /*
     * The core theme scss needs the !default attribute added to every style
     * to allow for overriding in medicare,
     * @TODO: get all systems on the same page and remove this
     */
    const defaultInclude = file.baseName.includes('core') ? ' !default' : '';

    output += formatTokensAsCssVars(
      tokenItems,
      section,
      (name, value) => {
        if (variableIgnoreList.includes(name)) {
          return `$${name}: ${value}${defaultInclude};\n`;
        }

        return `$${name}: var(--${name})${defaultInclude};\n`;
      },
      sep
    );
  });

  writeFile(filename, output);
};

/**
 * Writes a .css file that maps a css variable to its value
 * The definition of the css variables is scoped to a css selector `[data-theme=""]`
 *
 * @param filename - name of file to be created
 * @param file -  a single FileDescriptor item generated by getFileDescriptors
 * @param importedModule - module data
 * @param sep - separator string between prefix and key
 */
const writeCssVars = (filename: string, file: FileDescriptor, importedModule: any, sep: string) => {
  let tokenItems: Record<string, any>;

  // for core theme, need to scope to root so that other themes can inherit any variables that they don't explicitly define
  let output = file.baseName.includes('core')
    ? `:root, :before{\n`
    : `[data-theme="${file.baseName.replace('-components', '')}"]{\n`;

  Object.entries(importedModule.default).forEach(([section]) => {
    tokenItems = flatten(importedModule.default[section]);

    output += formatTokensAsCssVars(
      tokenItems,
      section,
      (name, value) => {
        if (variableIgnoreList.includes(name)) {
          return '';
        }
        return `--${name}: ${value};\n`;
      },
      sep
    );
  });

  output += '}';

  writeFile(filename, output);
};

/**
 * Accepts an array of file descriptors generated by getFileDescriptors('path')
 * and writes their imported data to filesystem as a Sass (SCSS) & CSS files
 *
 * This functionality is only concerned with component variables having a css variable map.
 *
 * @param fileDescriptors - An array of fileDescriptors generated by getFileDescriptors
 * @param outPath - The output path for the CSV file(s)
 * @returns An exit code based on success writing output
 */
export const exportCssVars = (fileDescriptors: FileDescriptor[], outPath: string): number => {
  fileDescriptors.forEach((file) => {
    const importedModule = require(`${file.moduleImportName}`);
    // component files do not need a separator
    const sep = file.baseName.includes('components') ? '' : '-';

    const scssToCssMapFilename = `${outPath}/${file.baseName}-scss-to-css.map.scss`;
    const cssVarFilename = `${outPath}/${file.baseName}-theme.css`;
    writeMap(scssToCssMapFilename, file, importedModule, sep);
    writeCssVars(cssVarFilename, file, importedModule, sep);
  });

  return 0;
};

export default exportCssVars;
