import { FileDescriptor } from './types';
import { flatten, writeFile } from './utility';

const tokenFormat = (name: string, value: string | unknown) => {
  return `$${name}: ${value};\n`;
};

const setVars = (items: Record<string, any>) => {
  let vars = '';
  Object.entries(items).forEach(([name, value]) => {
    vars += tokenFormat(name, value);
  });
  return vars;
};

/*
 * Accepts an array of file descriptors generated by getFileDescriptors('path')
 * and writes their imported data to the filesystem as Sass formatted scss files
 */
export const exportScss = (fileDescriptors: FileDescriptor[], outPath: string): number => {
  fileDescriptors.forEach((file) => {
    /*
     * doing this asynchronously with import() makes this code needlessly complex
     * so ignoring this particular linting error here to allow named require.
     * which runs synchronously.
     */
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const importedModule = require(`${file.moduleImportName}`);
    const filename = `${outPath}/${file.exportFileName}.scss`;
    let output = '';
    let type = 'tokens';

    if (importedModule.default.description) type = 'theme';

    if (type === 'theme') {
      Object.entries(importedModule.default).forEach(([key]) => {
        if (key === 'description') return;

        const tokenItems = flatten(importedModule.default[key], '', {}, '-', false);
        output += setVars(tokenItems);
      });
    } else {
      const tokens = flatten(importedModule.default, '', {}, '-', true);
      output = setVars(tokens);
    }

    writeFile(filename, output);
  });
  return 0;
};

export default exportScss;
