import { FileDescriptor } from './types';
import { flatten } from './utility';
import { writeFile } from './file';

/**
 * Formats an object containing key/value token pairs as a single string containing
 * the formatted values ready to be written to a SCSS file, including line breaks
 *
 * @param items - The object containing the key/value pairs
 * @param prefix - The prefix to be appended to each key on export
 * @param formatter - A function which takes a key, value and returns a formatted key, value string
 * @param separator - The separator between the prefix and key
 * @returns A string which contains all formatted key/value pairs
 */
const formatTokensAsCssVars = (
  items: Record<string, any>,
  prefix: string,
  formatter: (name: string, value: string) => string,
  separator: string
): string => {
  let SCSS = '';
  Object.entries(items).forEach(([name, value]) => {
    // global objects in themes are not prefixed by the token type
    name = prefix === 'global' ? name : `${prefix}${separator}${name}`;
    SCSS += formatter(name, value);
  });
  return SCSS;
};

const writeMap = (filename: string, file: FileDescriptor, importedModule: any, sep: string) => {
  let tokenItems: Record<string, any>;
  let output = '';

  Object.entries(importedModule.default).forEach(([section]) => {
    tokenItems = flatten(importedModule.default[section]);
    /*
     * The core theme scss needs the !default attribute added to every style
     * to allow for overriding in medicare,
     * @TODO: get all systems on the same page and remove this
     */
    const defaultInclude = file.baseName.includes('core') ? ' !default' : '';

    output += formatTokensAsCssVars(
      tokenItems,
      section,
      (n, v) => `$${n}: var(--${n})${defaultInclude};\n`,
      sep
    );
  });

  writeFile(filename, output);
};

const writeCssVars = (filename: string, file: FileDescriptor, importedModule: any, sep: string) => {
  let tokenItems: Record<string, any>;
  let output = `[data-theme="${file.baseName.replace('-components', '')}"]{\n`;

  Object.entries(importedModule.default).forEach(([section]) => {
    tokenItems = flatten(importedModule.default[section]);

    output += formatTokensAsCssVars(tokenItems, section, (n, v) => `--${n}: ${v};\n`, sep);
  });

  output += '}';

  writeFile(filename, output);
};

/**
 * Accepts an array of file descriptors generated by getFileDescriptors('path')
 * and writes their imported data to filesystem as a Sass (SCSS) file
 * Token files are combined into a single file, theme files are written separately.
 *
 * @param fileDescriptors - An array of fileDescriptors generated by getFileDescriptors
 * @param outPath - The output path for the CSV file(s)
 * @returns An exit code based on success writing output
 */
export const exportCssVars = (fileDescriptors: FileDescriptor[], outPath: string): number => {
  fileDescriptors.forEach((file) => {
    const importedModule = require(`${file.moduleImportName}`);
    // component files do not need a separator
    const sep = file.baseName.includes('components') ? '' : '-';

    if (file.baseName.includes('components')) {
      writeMap(`${outPath}/${file.baseName}-scss-to-css.map.scss`, file, importedModule, sep);
      writeCssVars(`${outPath}/${file.baseName}-theme.css`, file, importedModule, sep);
    }
  });

  //   if (fileDescriptors[0].parentDirectoryName.includes('tokens')) {
  //     writeFile(filename, tokenOutput);
  //   }

  return 0;
};

export default exportCssVars;
