/**
 * Render the component example and the JSON documentation (generated by
 * react-docgen)
 */

import React from 'react';
import ReactComponentExample from './ReactComponentExample';
import ReactPropDocs from './ReactPropDocs';

class ReactComponentDoc extends React.PureComponent {
  renderExample() {
    const renderComponent = require(`../../../node_modules/${this.props.packagePath}.example.jsx`).default;
    return <ReactComponentExample renderComponent={renderComponent} />;
  }

  render() {
    return (
      <section>
        <div dangerouslySetInnerHTML={{__html: this.props.description}} />
        {this.renderExample()}
        <h3>Props</h3>
        <ReactPropDocs propDocs={this.props.propDocs} />
      </section>
    );
  }
}

ReactComponentDoc.propTypes = {
  description: React.PropTypes.string,
  packagePath: React.PropTypes.string.isRequired,
  /* eslint-disable react/forbid-prop-types */
  propDocs: React.PropTypes.object
};

export default ReactComponentDoc;
