/**
 * Render the component example and the JSON documentation (generated by
 * react-docgen)
 */

import React from 'react';
import ReactComponentExample from './ReactComponentExample';
import ReactPropDocs from './ReactPropDocs';

class ReactComponentDoc extends React.Component {
  renderExample() {
    const renderComponent = require(`../../../node_modules/${this.props.packagePath}.example.jsx`).default;
    return <ReactComponentExample renderComponent={renderComponent} />;
  }

  render() {
    return (
      <section>
        <h3>React</h3>
        <p><code>{this.props.componentPath}.jsx</code></p>

        {this.renderExample()}

        <p>{this.props.description}</p>
        <ReactPropDocs propDocs={this.props.propDocs} />
      </section>
    );
  }
}

ReactComponentDoc.propTypes = {
  componentPath: React.PropTypes.string.isRequired,
  description: React.PropTypes.string,
  packagePath: React.PropTypes.string.isRequired,
  /* eslint-disable react/forbid-prop-types */
  propDocs: React.PropTypes.object
};

export default ReactComponentDoc;
